// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/account/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/account/[...]').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/user.get').default>>>>
    }
    '/api/defective': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/defective').default>>>>
    }
    '/api/defective/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/defective/[...]').default>>>>
    }
    '/api/delivery': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delivery').default>>>>
    }
    '/api/delivery/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delivery/[...]').default>>>>
    }
    '/api/inventory': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory').default>>>>
    }
    '/api/jaedan': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/jaedan').default>>>>
    }
    '/api/jaedan/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/jaedan/[...]').default>>>>
    }
    '/api/product/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/product/[...]').default>>>>
    }
    '/api/production/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/production/[...]').default>>>>
    }
    '/api/products/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[...]').default>>>>
    }
    '/api/saleproduct': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/saleproduct').default>>>>
    }
    '/api/scannedBarcode': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/scannedBarcode').default>>>>
    }
    '/api/scannedBarcodes': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/scannedBarcodes').default>>>>
    }
    '/api/stock': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stock').default>>>>
    }
    '/api/stock/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stock/[...]').default>>>>
    }
    '/api/test_scannedBarcode/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test_scannedBarcode/[...]').default>>>>
    }
    '/api/user': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user').default>>>>
    }
    '/api/wondan/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/wondan/[...]').default>>>>
    }
    '/api/working_part/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/working_part/[...]').default>>>>
    }
    '/api/workOrder': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workOrder').default>>>>
    }
    '/api/workOrder/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/workOrder/[...]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}