--
-- 테이블 구조 `WONDAN_STORE`
--

CREATE TABLE `WONDAN_STORE` (
  `NO` int(11) NOT NULL,
  `REG_DATE` date NOT NULL DEFAULT current_timestamp(),
  `WONDAN_NAME` varchar(50) NOT NULL,
  `LOT_NO` varchar(50) NOT NULL,
  `LENGTH` int(20) NOT NULL,
  `REAL_LENGTH` int(20) NOT NULL,
  `SUPPLAY` varchar(50) DEFAULT NULL,
  `REG_ACCOUNG` varchar(50) DEFAULT NULL,
  `DEFECTIVE_LENGTH` int(20) DEFAULT NULL,
  `STATE` int(20) NOT NULL DEFAULT 0,
  `STATE_DATE` date NOT NULL DEFAULT current_timestamp(),
  `ETC` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `WONDAN_STORE`
  ADD PRIMARY KEY (`NO`),
  ADD UNIQUE KEY `LOT_NO` (`LOT_NO`),
  ADD KEY `WONDAN_NAME` (`WONDAN_NAME`);


ALTER TABLE `WONDAN_STORE`
  ADD CONSTRAINT `WONDAN_NAME` FOREIGN KEY (`WONDAN_NAME`) REFERENCES `WONDAN` (`WONDAN_NAME`);


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
ALTER TABLE `JAEDAN_REGIST`
  ADD CONSTRAINT `WORK_ORDER_NO` FOREIGN KEY (`WORK_ORDER_NO`) REFERENCES `WORKING_ORDER` (`NO`);

  ALTER TABLE `JAEDAN_REGIST`
  ADD CONSTRAINT `REG_ACCOUNT` FOREIGN KEY (`REG_ACCOUNT`) REFERENCES `ACCOUNT` (`NO`);