SELECT *
FROM WORKING_PART
JOIN ASSY_PART ON WORKING_PART.ASSY_PART_NAME = ASSY_PART.ASSY_PART_NAME
JOIN ASSY_SUB_PART ON WORKING_PART.ASSY_SUB_PART_NAME = ASSY_SUB_PART.ASSY_SUB_NAME
JOIN JAEDAN_PART ON WORKING_PART.JAEDAN_PART_NAME = JAEDAN_PART.JAEDAN_PART_NAME
JOIN WONDAN ON WORKING_PART.WONDAN_NAME = WONDAN.WONDAN_NAME;


SELECT *
FROM JAEDAN_REGIST
JOIN WORKING_ORDER ON JAEDAN_REGIST.WORK_ORDER_NO = WORKING_ORDER.NO
JOIN WONDAN_STORE ON JAEDAN_REGIST.WONDAN_STORE = WONDAN_STORE.NO;

SELECT *,
(SELECT WORKING_PART FROM WORKING_ORDER WHERE WORKING_ORDER.NO = JAEDAN_REGIST.WORK_ORDER_NO) AS WORKING_PART
FROM JAEDAN_REGIST
JOIN WORKING_ORDER ON JAEDAN_REGIST.WORK_ORDER_NO = WORKING_ORDER.NO
JOIN WONDAN_STORE ON JAEDAN_REGIST.WONDAN_STORE = WONDAN_STORE.


CREATE VIEW JAEDAN_WORKING_VIEW AS
SELECT JAEDAN_REGIST.NO AS JAEDAN_REGIST_NO, JAEDAN_REGIST.*, WORKING_ORDER.NO AS WORKING_ORDER_NO, WONDAN_STORE.NO AS WONDAN_STORE_NO,
(SELECT WORKING_PART FROM WORKING_ORDER WHERE WORKING_ORDER.NO = JAEDAN_REGIST.WORK_ORDER_NO) AS WORKING_PART
FROM JAEDAN_REGIST
JOIN WORKING_ORDER ON JAEDAN_REGIST.WORK_ORDER_NO = WORKING_ORDER.NO
JOIN WONDAN_STORE ON JAEDAN_REGIST.WONDAN_STORE = WONDAN_STORE.NO;

SELECT *
FROM WORKING_ORDER
JOIN WORKING_PART ON WORKING_ORDER.WORKING_PART = WORKING_PART.ID;



CREATE VIEW WORKING_ORDER_PART_VIEW AS
SELECT *
FROM WORKING_ORDER
JOIN WORKING_PART ON WORKING_ORDER.WORKING_PART = WORKING_PART.ID;

ALTER TABLE `WORKING_ORDER`
  ADD CONSTRAINT `ACCOUNT` FOREIGN KEY (`ORDER_ACCOUNT`) REFERENCES `ACCOUNT` (`ID`),
  ADD CONSTRAINT `WORKING_PART` FOREIGN KEY (`WORKING_PART`) REFERENCES `WORKING_PART` (`ID`);
COMMIT;

ALTER TABLE `WORKING_ORDER`
  ADD CONSTRAINT `ACCOUNT` FOREIGN KEY (`REG_ACCOUNT`) REFERENCES `ACCOUNT` (`NO`);