ALTER TABLE JEADAN_WORK
ADD INDEX idx_WORK_ORDER_NO (WORK_ORDER_NO);


ALTER TABLE WORK_ORDER ADD CONSTRAINT idx_PART_NAME FOREIGN KEY (PART_NAME) REFERENCES PD_PART_NAME (PART_NAME);


ALTER TABLE JEADAN_WORK ADD CONSTRAINT fk_WORK_ORDER_NO FOREIGN KEY (WORK_ORDER_NO) REFERENCES WORK_ORDER (NO);

ALTER TABLE `WONDAN_STORE`
  ADD CONSTRAINT `fk_WONDAN_CODE` FOREIGN KEY (`CODE`) REFERENCES `WONDAN` (`CODE`);


SELECT JEADAN_WORK.*, WORK_ORDER.no, WORK_ORDER.part_name
FROM JEADAN_WORK
JOIN WORK_ORDER ON JEADAN_WORK.WORK_ORDER_NO = WORK_ORDER.NO;

CREATE VIEW JEADAN_WORK_WITH_WORK_ORDER AS
SELECT JEADAN_WORK.*, WORK_ORDER.no, WORK_ORDER.part_name
FROM JEADAN_WORK
JOIN WORK_ORDER ON JEADAN_WORK.WORK_ORDER_NO = WORK_ORDER.NO;

ALTER TABLE WORK_ORDER
ADD CONSTRAINT fk_PART_NAME
FOREIGN KEY (PART_NAME) REFERENCES PD_PART_NAME (PART_NAME);


MySQL phpMyAdmin에서 JEADAN_WORK 테이블의 LOT_NO 열에 입력되는 값이 WONDAN_STORE 테이블의 STATE 의 값이 0 인 LOT_NO 열의 값만 입력되도록 설정하려면 
ChatGPT
MySQL phpMyAdmin에서 JEADAN_WORK 테이블의 LOT_NO 열에 입력되는 값이 WONDAN_STORE 테이블에서 STATE 값이 0인 LOT_NO 열의 값만 입력되도록 설정하려면 다음과 같은 단계를 따를 수 있습니다:

먼저, WONDAN_STORE 테이블에서 STATE 값이 0인 LOT_NO 열에 대한 인덱스를 생성합니다:
sql
Copy code
ALTER TABLE WONDAN_STORE
ADD INDEX idx_state_lot_no (STATE, LOT_NO);
그런 다음, JEADAN_WORK 테이블의 LOT_NO 열을 외래 키로 설정하여 WONDAN_STORE 테이블의 STATE 값이 0인 LOT_NO 열과 매핑될 수 있도록 합니다:
sql
Copy code
ALTER TABLE JEADAN_WORK
ADD CONSTRAINT fk_WONDAN_STORE_LOT_NO
FOREIGN KEY (LOT_NO) REFERENCES WONDAN_STORE (LOT_NO)
ON DELETE CASCADE
ON UPDATE CASCADE;
이제 JEADAN_WORK 테이블의 LOT_NO 열에는 WONDAN_STORE 테이블에서 STATE 값이 0인 LOT_NO 열의 값만 입력될 수 있습니다.




번역된 내용

MySQL phpMyAdmin에서 JEADAN_WORK 테이블의 LOT_NO 열에 입력되는 값이 WONDAN_STORE 테이블에서 STATE 값이 0인 LOT_NO 열의 값만 입력되도록 설정하려면 다음과 같은 단계를 따를 수 있습니다:

먼저, WONDAN_STORE 테이블에서 STATE 값이 0인 LOT_NO 열에 대한 인덱스를 생성합니다:
sql
Copy code
ALTER TABLE WONDAN_STORE
ADD INDEX idx_state_lot_no (STATE, LOT_NO);
그런 다음, JEADAN_WORK 테이블의 LOT_NO 열을 외래 키로 설정하여 WONDAN_STORE 테이블의 STATE 값이 0인 LOT_NO 열과 매핑될 수 있도록 합니다:
sql
Copy code
ALTER TABLE JEADAN_WORK
ADD CONSTRAINT fk_WONDAN_STORE_LOT_NO
FOREIGN KEY (LOT_NO) REFERENCES WONDAN_STORE (LOT_NO)
ON DELETE CASCADE
ON UPDATE CASCADE;
이제 JEADAN_WORK 테이블의 LOT_NO 열에는 WONDAN_STORE 테이블에서 STATE 값이 0인 LOT_NO 열의 값만 입력될 수 있습니다.

