
interface _GlobalComponents {
      'BarCharts copy': typeof import("../components/BarCharts copy.vue")['default']
    'BarCharts': typeof import("../components/BarCharts.vue")['default']
    'BarChartsDefault': typeof import("../components/BarCharts_default.vue")['default']
    'FormLoginForm': typeof import("../components/Form/LoginForm.vue")['default']
    'FormLoginForm1': typeof import("../components/Form/LoginForm1.vue")['default']
    'FormLoginFormStore저장완성': typeof import("../components/Form/LoginForm_store저장완성.vue")['default']
    'FormLogin2': typeof import("../components/Form/login2.vue")['default']
    'JadanDetailModal': typeof import("../components/JadanDetailModal.vue")['default']
    'JadanDetailModal원본': typeof import("../components/JadanDetailModal원본.vue")['default']
    'LineChart': typeof import("../components/LineChart.client.vue")['default']
    'LineCharts copy': typeof import("../components/LineCharts copy.vue")['default']
    'LineCharts': typeof import("../components/LineCharts.vue")['default']
    'ModalComponent': typeof import("../components/ModalComponent.vue")['default']
    'PieCharts copy': typeof import("../components/PieCharts copy.vue")['default']
    'PieCharts': typeof import("../components/PieCharts.vue")['default']
    'ToExcel': typeof import("../components/ToExcel.vue")['default']
    'WondanEdit': typeof import("../components/WondanEdit.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LineChart': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
      'LazyBarCharts copy': typeof import("../components/BarCharts copy.vue")['default']
    'LazyBarCharts': typeof import("../components/BarCharts.vue")['default']
    'LazyBarChartsDefault': typeof import("../components/BarCharts_default.vue")['default']
    'LazyFormLoginForm': typeof import("../components/Form/LoginForm.vue")['default']
    'LazyFormLoginForm1': typeof import("../components/Form/LoginForm1.vue")['default']
    'LazyFormLoginFormStore저장완성': typeof import("../components/Form/LoginForm_store저장완성.vue")['default']
    'LazyFormLogin2': typeof import("../components/Form/login2.vue")['default']
    'LazyJadanDetailModal': typeof import("../components/JadanDetailModal.vue")['default']
    'LazyJadanDetailModal원본': typeof import("../components/JadanDetailModal원본.vue")['default']
    'LazyLineChart': typeof import("../components/LineChart.client.vue")['default']
    'LazyLineCharts copy': typeof import("../components/LineCharts copy.vue")['default']
    'LazyLineCharts': typeof import("../components/LineCharts.vue")['default']
    'LazyModalComponent': typeof import("../components/ModalComponent.vue")['default']
    'LazyPieCharts copy': typeof import("../components/PieCharts copy.vue")['default']
    'LazyPieCharts': typeof import("../components/PieCharts.vue")['default']
    'LazyToExcel': typeof import("../components/ToExcel.vue")['default']
    'LazyWondanEdit': typeof import("../components/WondanEdit.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyLineChart': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BarCharts copy: typeof import("../components/BarCharts copy.vue")['default']
export const BarCharts: typeof import("../components/BarCharts.vue")['default']
export const BarChartsDefault: typeof import("../components/BarCharts_default.vue")['default']
export const FormLoginForm: typeof import("../components/Form/LoginForm.vue")['default']
export const FormLoginForm1: typeof import("../components/Form/LoginForm1.vue")['default']
export const FormLoginFormStore저장완성: typeof import("../components/Form/LoginForm_store저장완성.vue")['default']
export const FormLogin2: typeof import("../components/Form/login2.vue")['default']
export const JadanDetailModal: typeof import("../components/JadanDetailModal.vue")['default']
export const JadanDetailModal원본: typeof import("../components/JadanDetailModal원본.vue")['default']
export const LineChart: typeof import("../components/LineChart.client.vue")['default']
export const LineCharts copy: typeof import("../components/LineCharts copy.vue")['default']
export const LineCharts: typeof import("../components/LineCharts.vue")['default']
export const ModalComponent: typeof import("../components/ModalComponent.vue")['default']
export const PieCharts copy: typeof import("../components/PieCharts copy.vue")['default']
export const PieCharts: typeof import("../components/PieCharts.vue")['default']
export const ToExcel: typeof import("../components/ToExcel.vue")['default']
export const WondanEdit: typeof import("../components/WondanEdit.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LineChart: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyBarCharts copy: typeof import("../components/BarCharts copy.vue")['default']
export const LazyBarCharts: typeof import("../components/BarCharts.vue")['default']
export const LazyBarChartsDefault: typeof import("../components/BarCharts_default.vue")['default']
export const LazyFormLoginForm: typeof import("../components/Form/LoginForm.vue")['default']
export const LazyFormLoginForm1: typeof import("../components/Form/LoginForm1.vue")['default']
export const LazyFormLoginFormStore저장완성: typeof import("../components/Form/LoginForm_store저장완성.vue")['default']
export const LazyFormLogin2: typeof import("../components/Form/login2.vue")['default']
export const LazyJadanDetailModal: typeof import("../components/JadanDetailModal.vue")['default']
export const LazyJadanDetailModal원본: typeof import("../components/JadanDetailModal원본.vue")['default']
export const LazyLineChart: typeof import("../components/LineChart.client.vue")['default']
export const LazyLineCharts copy: typeof import("../components/LineCharts copy.vue")['default']
export const LazyLineCharts: typeof import("../components/LineCharts.vue")['default']
export const LazyModalComponent: typeof import("../components/ModalComponent.vue")['default']
export const LazyPieCharts copy: typeof import("../components/PieCharts copy.vue")['default']
export const LazyPieCharts: typeof import("../components/PieCharts.vue")['default']
export const LazyToExcel: typeof import("../components/ToExcel.vue")['default']
export const LazyWondanEdit: typeof import("../components/WondanEdit.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyLineChart: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']

export const componentNames: string[]
